ALTER TABLE orders ADD COLUMN duration_days INTEGER NOT NULL DEFAULT 30;
ALTER TABLE orders ADD COLUMN quota_bytes INTEGER NOT NULL DEFAULT 1;
ALTER TABLE orders ADD COLUMN node_pool_bps INTEGER NOT NULL DEFAULT 0;
